/** Brand specs for every Fun Toy. Palettes stay distinct on purpose. */

export const ROOT = new URL("../../", import.meta.url);

export const TOYS = [
  {
    id: "fun-toys",
    name: "Fun Toys",
    acc: "FT",
    live: "https://fun-toys-alpha.vercel.app",
    out: "fun-toys",
    publicDir: ".",
    bg: "#1a120c",
    fg: "#ead9b8",
    accent: "#c4a35a",
    word: "CABINET",
  },
  {
    id: "cursorling",
    name: "Cursorling",
    acc: "FT–001",
    live: "https://cursorling.vercel.app",
    out: "cursorling",
    publicDir: "public",
    bg: "#1a0e0a",
    fg: "#f4ebd8",
    accent: "#c4a574",
    word: "INK",
  },
  {
    id: "please-press",
    name: "THE BUTTON.",
    acc: "FT–002",
    live: "https://please-press.vercel.app",
    out: "please-press",
    publicDir: "public",
    bg: "#f4f0e6",
    fg: "#16140f",
    accent: "#1c1a16",
    word: "PRESS",
  },
  {
    id: "plot-armor",
    name: "Plot Armor",
    acc: "FT–003",
    live: "https://plot-armor-livid.vercel.app",
    out: "plot-armor",
    publicDir: "public",
    bg: "#1a0f14",
    fg: "#f6ead2",
    accent: "#e4c07a",
    word: "DRAW",
  },
  {
    id: "vapor-market",
    name: "Vapor Market",
    acc: "FT–004",
    live: "https://vapor-market.vercel.app",
    out: "vapor-market",
    publicDir: "public",
    bg: "#efeae1",
    fg: "#1c1916",
    accent: "#5b4dff",
    word: "INVENT",
  },
  {
    id: "grandiose",
    name: "Grandiose",
    acc: "FT–005",
    live: "https://grandiose-seven.vercel.app",
    out: "grandiose",
    publicDir: "public",
    bg: "#050505",
    fg: "#f3e5ab",
    accent: "#d4af37",
    word: "PREMIERE",
  },
  {
    id: "term-specter",
    name: "Specter",
    acc: "FT–006",
    live: "https://term-specter.vercel.app",
    out: "term-specter",
    publicDir: "web",
    bg: "#1a1220",
    fg: "#e8d4f0",
    accent: "#c9a0dc",
    word: "HAUNT",
  },
  {
    id: "chimemoji",
    name: "Chimemoji",
    acc: "FT–007",
    live: "https://chimemoji.vercel.app",
    out: "chimemoji",
    publicDir: "public",
    bg: "#12140e",
    fg: "#8dff7a",
    accent: "#c4a035",
    word: "FUSE",
  },
  {
    id: "mild-inconvenience",
    name: "Mild Inconvenience",
    acc: "FT–008",
    live: "https://mild-inconvenience.vercel.app",
    out: "mild-inconvenience",
    publicDir: "public",
    bg: "#f3efe4",
    fg: "#1c2f4a",
    accent: "#1c2f4a",
    word: "BULLETIN",
  },
  {
    id: "peel-pack",
    name: "Peel Pack",
    acc: "FT–009",
    live: "https://peel-pack.vercel.app",
    out: "peel-pack",
    publicDir: "public",
    bg: "#fff6fb",
    fg: "#1a1230",
    accent: "#ff4d8d",
    word: "PEEL",
  },
  {
    id: "still-here",
    name: "Still Here",
    acc: "FT–010",
    live: "https://still-here-psi.vercel.app",
    out: "still-here",
    publicDir: "public",
    bg: "#c9c3b6",
    fg: "#14110e",
    accent: "#14110e",
    word: "STILL",
  },
  {
    id: "rake-garden",
    name: "Rake",
    acc: "FT–011",
    live: "https://rake-garden.vercel.app",
    out: "rake-garden",
    publicDir: "public",
    bg: "#efe6d4",
    fg: "#2b261f",
    accent: "#cbb99a",
    word: "RAKE",
  },
  {
    id: "the-elsewhere",
    name: "The Elsewhere",
    acc: "FT–012",
    live: "https://the-elsewhere.vercel.app",
    out: "the-elsewhere",
    publicDir: "public",
    bg: "#f4ead8",
    fg: "#6e2c24",
    accent: "#8d6e44",
    word: "ELSEWHERE",
  },
  {
    id: "elsewho",
    name: "Elsewho",
    acc: "FT–013",
    live: "https://elsewho.vercel.app",
    out: "elsewho",
    publicDir: "public",
    bg: "#1b1410",
    fg: "#efe2cc",
    accent: "#c45c26",
    word: "PRINT",
  },
  {
    id: "jigmoji",
    name: "Jigmoji",
    acc: "FT–014",
    live: "https://jigmoji.vercel.app",
    out: "jigmoji",
    publicDir: "public",
    bg: "#ffe14a",
    fg: "#14182a",
    accent: "#ff3d6e",
    word: "JINGLE",
  },
  {
    id: "mood-pointer",
    name: "Mood Pointer",
    acc: "FT–015",
    live: "https://mood-pointer.vercel.app",
    out: "mood-pointer",
    publicDir: "public",
    bg: "#12141a",
    fg: "#b8f0c8",
    accent: "#c5c8d0",
    word: "MOOD",
  },
  {
    id: "pixel-penance",
    name: "Pixel Penance",
    acc: "FT–016",
    live: "https://pixel-penance.vercel.app",
    out: "pixel-penance",
    publicDir: "public",
    bg: "#f7f1e1",
    fg: "#2b2118",
    accent: "#e07a3d",
    word: "PIXEL",
  },
  {
    id: "pet-the-void",
    name: "Pet the Void",
    acc: "FT–017",
    live: "https://pet-the-void.vercel.app",
    out: "pet-the-void",
    publicDir: "public",
    bg: "#07060a",
    fg: "#ece6dc",
    accent: "#c4a574",
    word: "VOID",
  },
  {
    id: "hunted-404",
    name: "Hunted 404",
    acc: "FT–018",
    live: "https://hunted-404.vercel.app",
    out: "hunted-404",
    publicDir: "public",
    bg: "#111111",
    fg: "#f2f2f2",
    accent: "#ff4d4d",
    word: "404",
  },
];

export function destDir(toy, { dry = false } = {}) {
  const kit = new URL("../", import.meta.url);
  if (dry) return new URL(`../dist/${toy.id}/`, import.meta.url);
  return new URL(`../${toy.out}/${toy.publicDir}/`, kit);
}
